### PR TITLE
Update l10n_nl.xml

### PR DESCRIPTION
**Pull request by joshvzeyl**
Here is the dutch translation for you guys, i'm very exited to see the machine it self in action, so my question is is the mod from the here working in game so that i can take a short sneekpeak of the mod.

### CODE REVIEW

**Comment by Dzi4d3k** [comment]
@joshvzeyl it is not working "some" files are missing :)

**Comment by joshvzeyl** [comment]
okay, no problem i will take an look at link with the brochures you sended

**Comment by joshvzeyl** [comment]
the last update file is the right one

**Comment by TyKonKet** [comment]
I'm sorry but we have no intention to provide the full version first of the release for the mod contest, after 6 moths of hard work, we can't risk stealings.

**Comment by joshvzeyl** [comment]
No problem, i understand and will wait until the full release during the modcontest keep up the good work, I also looked the machine up on YouTube and I looks great In real life

**Pull request merged**
